### ISSUE TITLE
U1 footprint

### ISSUE THREAD

**Issue by reinauer** [hanshuebner/ipx-psu-replacement#3]
The PCB silkscreen suggests that U1 is a 74hct27 nor gate. But the BOM talks about a 74hct11 and gate for U1.

Which one is the correct part?

**Comment by hanshuebner** [comment]
What PCB silkscreen are you looking at?  From what I can tell, the version that is on GitHub has the 74HCT11, which is the correct part (48fba2ea6a64b1d7f49c5705dc5846d154136498).

**Comment by reinauer** [comment]
Hmmm I'm also not seeing the footprints for the 120ohm resistors.. were the gerbers not updated by any chance?

**Comment by hanshuebner** [comment]
Ah, you're looking at the Gerbers.  Thanks for pointing that out, I'll update them now.  Sorry!

**Comment by reinauer** [comment]
Yeah, silly me. I ordered a bunch of boards from the gerbers without checking.

**Comment by hanshuebner** [comment]
Sorry again!  You should be able to get the boards running anyway if you use a 74HCT11 and scrape off some of the solder mask to solder on the base load resistors.  The Gerbers are updated now, unfortunately too late for you.  Hope you get to revive your IP[CX] nevertheless.
